import React, { useMemo, useState } from "react";
import { Head, Link, router, usePage } from "@inertiajs/react";
import { ArrowLeft, Check, Edit3, LockKeyhole, Save, ShieldCheck, Trash2, User } from "lucide-react";
import AdminLayout from "../../../Layouts/AdminLayout";

export default function Detail({ userRecord, roles = [], permissions = [], backUrl = "/system/access-control" }) {
    const { flash = {}, errors = {} } = usePage().props;
    const [role, setRole] = useState(userRecord.role || "");
    const [directPermissions, setDirectPermissions] = useState(userRecord.directPermissions || []);
    const [processing, setProcessing] = useState(false);
    const selectedRolePermissions = useMemo(() => roles.find((item) => item.name === role)?.permissions || [], [roles, role]);
    const rolePermissionNames = useMemo(() => new Set(selectedRolePermissions), [selectedRolePermissions]);
    const isSuperAdmin = role === "super-admin";
    const availablePermissionNames = useMemo(() => permissions.filter((permission) => isSuperAdmin || !permission.superAdminOnly).map((permission) => permission.name), [isSuperAdmin, permissions]);
    const allPermissionNames = availablePermissionNames;
    const hasFullAccess = isSuperAdmin || allPermissionNames.every((name) => rolePermissionNames.has(name) || directPermissions.includes(name));

    const togglePermission = (permission) => { if (!isSuperAdmin && !permission.superAdminOnly && !rolePermissionNames.has(permission.name)) setDirectPermissions((current) => current.includes(permission.name) ? current.filter((item) => item !== permission.name) : [...current, permission.name]); };
    const toggleFullAccess = () => { if (!isSuperAdmin) setDirectPermissions(hasFullAccess ? [] : allPermissionNames.filter((name) => !rolePermissionNames.has(name))); };
    const saveAccess = () => { setProcessing(true); router.put(`/system/access-control/users/${userRecord.id}/access`, { role, permissions: directPermissions }, { preserveScroll: true, onFinish: () => setProcessing(false) }); };
    const destroy = () => { if (!userRecord.isCurrentUser && window.confirm(`Hapus pengguna ${userRecord.nik}?`)) router.delete(`/system/access-control/users/${userRecord.id}`); };

    return <AdminLayout><Head title={`Akses User - ${userRecord.nik}`} />
        <div className="space-y-5">
            <div className="flex flex-wrap items-center gap-2 text-sm font-semibold text-slate-500"><Link href="/dashboard" className="transition hover:text-violet-600">Dashboard</Link><span className="text-slate-300">/</span><Link href={backUrl} className="transition hover:text-violet-600">Role & Akses</Link><span className="text-slate-300">/</span><span className="truncate text-slate-900">{userRecord.nik}</span></div>
            <section className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/70 sm:p-7">
                <div className="pointer-events-none absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-violet-500 via-cyan-400 to-amber-300" />
                <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-start gap-3"><Link href={backUrl} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-slate-50 text-slate-700 transition hover:border-violet-200 hover:bg-violet-50 hover:text-violet-700"><ArrowLeft size={18} /></Link><div className="min-w-0"><div className="inline-flex items-center gap-2 rounded-lg bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700"><User size={15} /> Profil pengguna</div><h1 className="mt-3 break-words text-2xl font-extrabold tracking-tight text-slate-950 sm:text-3xl">{userRecord.nik}</h1><p className="mt-1 break-all text-sm text-slate-600">{userRecord.email}</p></div></div><div className="flex flex-wrap gap-2"><Link href={`/system/access-control/users/${userRecord.id}/edit`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white shadow-sm transition hover:bg-violet-700"><Edit3 size={16} />Edit user</Link>{!userRecord.isCurrentUser && <button type="button" onClick={destroy} className="inline-flex h-11 items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 text-sm font-bold text-rose-700 transition hover:bg-rose-600 hover:text-white"><Trash2 size={16} />Hapus</button>}</div></div>
            </section>
            {flash.success && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><Check size={17} />{flash.success}</div>}
            {Object.values(errors).map((error) => <div key={error} className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>)}
            <div className="grid gap-5 xl:grid-cols-[minmax(0,0.72fr)_minmax(0,1.28fr)]">
                <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/60"><div className="flex items-center gap-2"><User size={19} className="text-violet-600" /><h2 className="text-base font-extrabold text-slate-950">Role utama</h2></div><p className="mt-1 text-sm leading-6 text-slate-500">Role memberi izin dasar. Izin tambahan dapat diatur pada panel sebelah.</p><label className="mt-5 block"><span className="mb-2 block text-xs font-semibold text-slate-600">Role pengguna</span><select id="access-control-role" name="access-control-role" value={role} onChange={(event) => { setRole(event.target.value); setDirectPermissions([]); }} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-semibold text-slate-700 outline-none focus:border-violet-400 focus:bg-white focus:ring-2 focus:ring-violet-200/50">{roles.map((item) => <option key={item.name} value={item.name}>{item.label}</option>)}</select></label><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Izin dari role aktif</p><p className="mt-1 text-2xl font-extrabold tabular-nums text-slate-950">{selectedRolePermissions.length}</p></div></section>
                <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/60"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><LockKeyhole size={19} className="text-violet-600" /><h2 className="text-base font-extrabold text-slate-950">Akses pengguna</h2></div><p className="mt-1 text-sm leading-6 text-slate-500">Izin dari role aktif otomatis. Centang izin tambahan khusus untuk pengguna ini.</p></div><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{permissions.length} izin</span></div><label className={`mt-5 flex items-center justify-between gap-4 rounded-xl border p-4 ${hasFullAccess ? "border-emerald-200 bg-emerald-50" : "border-slate-200 bg-slate-50"}`}><span className="min-w-0"><span className="flex items-center gap-2 text-sm font-bold text-slate-950"><ShieldCheck size={17} />Akses penuh semua modul</span><span className="mt-1 block text-xs leading-5 text-slate-500">Satu pilihan untuk akses baca dan kelola seluruh modul yang boleh dipakai role ini.</span></span><input id="access-control-full-access" name="access-control-full-access" type="checkbox" checked={hasFullAccess} disabled={isSuperAdmin} onChange={toggleFullAccess} className="h-5 w-5 shrink-0 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500" /></label><div className="mt-4 grid gap-3 sm:grid-cols-2">{permissions.map((permission) => { const lockedForRole = permission.superAdminOnly && !isSuperAdmin; const inherited = isSuperAdmin || rolePermissionNames.has(permission.name); const checked = inherited || directPermissions.includes(permission.name); return <label key={permission.name} className={`flex min-w-0 items-start gap-3 rounded-xl border p-3 ${lockedForRole ? "border-amber-200 bg-amber-50/70" : checked ? "border-violet-200 bg-violet-50/60" : "border-slate-200 bg-white"}`}><input id={`permission-${permission.name}`} name={`permission-${permission.name}`} type="checkbox" checked={checked && !lockedForRole} disabled={inherited || lockedForRole} onChange={() => togglePermission(permission)} className="mt-0.5 rounded border-slate-300 text-violet-600 focus:ring-violet-500" /><span className="min-w-0"><span className="block text-sm font-bold text-slate-800">{permission.label}</span><span className="mt-0.5 block break-all text-[11px] text-slate-400">{lockedForRole ? "Khusus Super Admin" : inherited ? "Dari role" : permission.name}</span></span></label>; })}</div><div className="mt-5 flex justify-end"><button type="button" disabled={processing} onClick={saveAccess} className="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white transition hover:bg-violet-700 disabled:opacity-50"><Save size={16} />Simpan akses</button></div></section>
            </div>
        </div>
    </AdminLayout>;
}
