<?php

return [
    'biaya-inventori' => [
        'label' => 'Biaya Legalitas Unit',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'biaya.manage',
        'back' => '/biaya',
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'project', 'tahun', 'tahun_pembelian', 'distribusi', 'status', 'keterangan',
            'jatuh_tempo_stnk', 'masa_aktif_stnk', 'status_stnk', 'biaya_stnk',
            'jatuh_tempo_pajak', 'masa_aktif_pajak', 'status_pajak', 'biaya_pajak',
            'jatuh_tempo_kir', 'masa_aktif_kir', 'status_kir', 'biaya_kir',
        ],
    ],
    'profit-primary' => [
        'label' => 'Profit Primary',
        'table' => 'operasional_primary_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/primary',
        'fields' => [
            'no_bap', 'regional', 'area', 'week', 'tanggal_muat', 'tanggal_terima', 'rute_asal', 'rute_tujuan',
            'vendor', 'nopol_driver', 'qty', 'jenis', 'total', 'no_po', 'no_si', 'no_sj', 'tarif',
            'total_tarif', 'tarif_vendor', 'biaya_buruh_muat', 'biaya_buruh_bongkar', 'biaya_dooring',
            'biaya_kapal', 'biaya_bbm', 'biaya_transport', 'biaya_lain_lain', 'total_biaya', 'productivity',
            'profit', 'keterangan', 'create_data', 'status_dokument', 'tanggal_dokument_naik',
        ],
        'import_enabled' => true,
        'import_required' => ['tanggal_muat', 'area', 'total_tarif'],
        'import_uppercase' => ['no_bap', 'regional', 'area', 'rute_asal', 'rute_tujuan', 'vendor', 'nopol_driver', 'jenis', 'no_po', 'no_si', 'no_sj', 'status_dokument'],
        'import_date' => ['tanggal_muat', 'tanggal_terima'],
        'import_unique_dates' => ['tanggal_muat'],
        'import_datetime' => ['create_data', 'tanggal_dokument_naik'],
        'import_numeric' => [
            'week', 'qty', 'total', 'tarif', 'total_tarif', 'tarif_vendor', 'biaya_buruh_muat',
            'biaya_buruh_bongkar', 'biaya_dooring', 'biaya_kapal', 'biaya_bbm', 'biaya_transport',
            'biaya_lain_lain', 'productivity',
        ],
        'import_text' => ['no_bap', 'no_po', 'no_si', 'no_sj'],
        'import_unique' => [['no_bap', 'no_si', 'no_sj', 'tanggal_muat', 'nopol_driver', 'total_tarif']],
        'import_calculations' => [
            'total_biaya' => [
                'operation' => 'sum',
                'fields' => [
                    'tarif_vendor', 'biaya_buruh_muat', 'biaya_buruh_bongkar', 'biaya_dooring',
                    'biaya_kapal', 'biaya_bbm', 'biaya_transport', 'biaya_lain_lain',
                ],
            ],
            'profit' => ['operation' => 'difference', 'left' => 'total_tarif', 'right' => 'total_biaya'],
        ],
        'import_instruction' => 'TOTAL BIAYA dan PROFIT dihitung otomatis dari tarif serta seluruh komponen biaya. Nilai profit dapat negatif bila biaya lebih besar dari tarif.',
    ],
    'profit-secondary' => [
        'label' => 'Profit Secondary',
        'table' => 'operasional_secondary_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/secondary',
        'fields' => [
            'no_po', 'no_si', 'hari', 'tanggal', 'bulan', 'tahun', 'week', 'jam_mulai', 'jam_selesai',
            'nopol', 'tipe_unit', 'area', 'driver', 'helper', 'qty', 'km_awal', 'km_akhir', 'order_type',
            'tarif_unit', 'total_tarif', 'add_cost_long_route', 'subsidi_bbm', 'tkbm', 'spsi',
            'parkir_liar_keamanan', 'allowance', 'biaya_tagihan_hotel', 'tarif_hotel', 'subsidi_hotel',
            'penyebrangan_pas_masuk', 'rapid_antigen', 'bbm', 'nominal_pengisian_bbm', 'jenis_bbm',
            'harga_perliter', 'jumlah_liter', 'odo_isi_bbm', 'non_claim_bbm', 'subsidi_bbm_2', 'tambah_bbm',
            'bbm_2', 'nominal_pengisian_bbm_2', 'jenis_bbm_2', 'harga_perliter_2', 'jumlah_liter_2',
            'odo_isi_bbm_2', 'non_claim_bbm_2', 'total_subsidi_bbm', 'total_non_klaim_bbm', 'parkir_resmi',
            'tarif_sewa_unit_vendor', 'tol', 'kirim_dokumen', 'atk', 'tarif_gs', 'biaya_lainnya',
            'total_biaya_operasional', 'status_dokument', 'tanggal_dokument_naik', 'region', 'status',
            'keterangan', 'rute', 'project', 'posisi_project', 'add_data',
        ],
        'import_enabled' => true,
        'import_required' => ['tanggal', 'tahun', 'week', 'nopol', 'area', 'project'],
        'import_uppercase' => ['no_po', 'no_si', 'nopol', 'tipe_unit', 'area', 'driver', 'helper', 'region', 'project', 'posisi_project', 'status_dokument', 'status'],
        'import_date' => ['tanggal'],
        'import_unique_dates' => ['tanggal'],
        'import_datetime' => ['tanggal_dokument_naik'],
        'import_numeric' => [
            'tahun', 'week', 'qty', 'km_awal', 'km_akhir', 'tarif_unit', 'total_tarif', 'add_cost_long_route',
            'subsidi_bbm', 'tkbm', 'spsi', 'parkir_liar_keamanan', 'allowance', 'biaya_tagihan_hotel',
            'tarif_hotel', 'subsidi_hotel', 'penyebrangan_pas_masuk', 'rapid_antigen', 'nominal_pengisian_bbm',
            'harga_perliter', 'jumlah_liter', 'odo_isi_bbm', 'non_claim_bbm', 'subsidi_bbm_2', 'tambah_bbm',
            'nominal_pengisian_bbm_2', 'harga_perliter_2', 'jumlah_liter_2', 'odo_isi_bbm_2', 'non_claim_bbm_2',
            'total_subsidi_bbm', 'total_non_klaim_bbm', 'parkir_resmi', 'tarif_sewa_unit_vendor', 'tol',
            'kirim_dokumen', 'atk', 'tarif_gs', 'biaya_lainnya', 'total_biaya_operasional',
        ],
        'import_text' => ['no_po', 'no_si'],
        'import_unique' => [['tanggal', 'nopol', 'no_po', 'no_si', 'project', 'total_tarif']],
        'import_instruction' => 'PROFIT TRIP, nilai OVT absensi, TAGIHAN, dan total no-klaim adalah nilai virtual AppSheet. Isi hanya data operasional fisik; sistem menghitung nilai tersebut saat laporan dibuka. TOTAL BIAYA OPERASIONAL berasal dari nominal biaya operasional yang sudah diverifikasi.',
    ],
    'profit-rental' => [
        'label' => 'Profit Rental',
        'table' => 'operasional_rental_unit_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/rental',
        'fields' => ['tanggal', 'no_bap', 'no_po', 'area', 'regional', 'nopol', 'tipe', 'tarif_sewa_unit_bln', 'biaya_legalitas'],
        'import_enabled' => true,
        'import_required' => ['tanggal', 'area', 'nopol', 'tipe', 'tarif_sewa_unit_bln'],
        'import_date' => ['tanggal'],
        'import_unique_dates' => ['tanggal'],
        'import_uppercase' => ['area', 'regional', 'nopol', 'tipe'],
        'import_numeric' => ['tarif_sewa_unit_bln', 'biaya_legalitas'],
        'import_text' => ['no_bap', 'no_po'],
        'import_unique' => [['tanggal', 'nopol', 'no_bap', 'no_po', 'tarif_sewa_unit_bln']],
        'import_instruction' => 'PROFIT RENTAL AppSheet dihitung dari penjumlahan TARIF SEWA UNIT BLN. Biaya legalitas tetap diisi untuk kebutuhan rincian biaya unit, tetapi tidak mengubah rumus Profit Rental AppSheet.',
    ],
    'profit-lcl' => [
        'label' => 'Profit LCL',
        'table' => 'db_chargo_data_paket_masuk',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/lcl',
        'fields' => [
            'no_stt', 'tanggal', 'tahun', 'bulan', 'week', 'kode_pesanan', 'nama_pengirim', 'kota_asal',
            'nama_penerima', 'kota_tujuan', 'total_koli', 'qty_unit', 'total_ongkir', 'jenis_ppn',
            'total_ppn', 'tagihan_cod', 'total_bayar', 'kembalian',
        ],
        'import_enabled' => true,
        'import_required' => ['no_stt', 'tanggal', 'tahun', 'bulan', 'week', 'nama_pengirim', 'kota_asal', 'nama_penerima', 'kota_tujuan', 'total_ongkir'],
        'import_date' => ['tanggal'],
        'import_uppercase' => ['no_stt', 'kota_asal', 'kota_tujuan', 'jenis_ppn'],
        'import_numeric' => ['tahun', 'week', 'total_koli', 'qty_unit', 'total_ongkir', 'total_ppn', 'tagihan_cod', 'total_bayar', 'kembalian'],
        'import_text' => ['no_stt', 'kode_pesanan'],
        'import_unique' => [['no_stt']],
        'import_instruction' => 'PROFIT LCL AppSheet dihitung dari penjumlahan TOTAL ONGKIR. NO STT wajib unik dan disimpan sebagai teks agar formatnya tidak berubah. Gunakan tanggal standar YYYY-MM-DD, misalnya 2026-09-06.',
    ],
    'unit-inventori' => [
        'label' => 'Daftar Unit',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-unit',
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'gps', 'no_mesin', 'no_rangka', 'driver', 'project', 'tahun', 'tahun_pembelian',
            'distribusi', 'status', 'keterangan',
        ],
    ],
    'pajak-inventori' => [
        'label' => 'Pajak dan STNK Unit',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/pajak',
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'project', 'tahun', 'tahun_pembelian', 'distribusi', 'status', 'keterangan',
            'jatuh_tempo_stnk', 'masa_aktif_stnk', 'status_stnk', 'biaya_stnk',
            'jatuh_tempo_pajak', 'masa_aktif_pajak', 'status_pajak', 'biaya_pajak',
            'jatuh_tempo_kir', 'masa_aktif_kir', 'status_kir', 'biaya_kir',
        ],
    ],
    'kendaraan-operasional' => [
        'label' => 'Kendaraan Operasional',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/kendaraan-operasional',
        'defaults' => [
            'project' => 'OPERASIONAL UNIT',
        ],
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'gps', 'no_mesin', 'no_rangka', 'driver', 'project', 'tahun', 'tahun_pembelian',
            'distribusi', 'status', 'keterangan', 'foto_unit', 'status_stnk', 'status_pajak',
            'status_kir', 'my_pertamina',
        ],
    ],
    'asset-ho' => [
        'label' => 'Asset HO',
        'table' => 'hr_manager_inventaris_laptop',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/asset-ho',
        'fields' => [
            'nama_pengguna', 'katagori', 'jenis_barang', 'model_unit', 'divisi', 'lokasi',
            'jumlah_unit', 'pengguna_sebelumnya', 'spesifikasi', 'status', 'warna',
            'gambar', 'serial_number', 'keterangan',
        ],
    ],
    'toolkit' => [
        'label' => 'Toolkit',
        'table' => 'operasional_checklist',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/toolkit',
        'fields' => [
            'tanggal', 'nopol', 'tipe_unit', 'area', 'driver', 'surat_kendaraan',
            'kebersihan_unit_kabin', 'kondisi_mesin_oli', 'service_berkala', 'air_radiator',
            'air_aki', 'kondisi_rem', 'indikator_dashboard', 'kondisi_kebersihan_box',
            'klakson', 'lampu_lampu', 'apar', 'safety_belt', 'p3k', 'dongkrak',
            'kunci_roda', 'engsel_pengunci_pintu', 'gembok', 'kondisi_ban',
            'tekanan_angin_ban', 'status_checklist', 'keluhan',
        ],
    ],
    'monitoring-unit' => [
        'label' => 'Monitoring Unit',
        'table' => 'operasional_update_posisi_unit',
        'key' => 'id',
        'permission' => 'on-the-road.manage',
        'back' => '/on-the-road',
        'fields' => ['tanggal_jam', 'nopol', 'nama_driver', 'location', 'keterangan'],
        'import_enabled' => true,
        'import_required' => ['tanggal_jam', 'nopol', 'location'],
        'import_datetime' => ['tanggal_jam'],
        'import_latlong' => ['location'],
        'import_uppercase' => ['nopol'],
        'import_references' => [
            'nopol' => [
                'table' => 'hr_manager_db_inventori',
                'column' => 'nopol',
                'label' => 'NOPOL',
            ],
        ],
        'import_unique' => [['nopol', 'tanggal_jam']],
        'import_instruction' => 'NOPOL wajib sudah terdaftar di inventori. Location diisi dalam format latitude,longitude, misalnya -6.175392,106.827153.',
    ],
    'operasional-absen' => [
        'label' => 'Absensi Operasional',
        'table' => 'operasional_absen',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records/operasional-absen',
        'fields' => [
            'nomer_si', 'nama', 'area', 'tanggal', 'bulan', 'waktu_masuk', 'waktu_pulang',
            'total_waktu_kerja', 'selisih_jam_kerja', 'status', 'keterangan', 'foto_masuk',
            'foto_pulang', 'maps_masuk', 'maps_pulang', 'jam_overtime', 'tarif_ovt', 'total_ovt',
            'email', 'lembur', 'approval_ovt', 'status_kerja', 'week', 'project',
        ],
    ],
    'service-umum' => [
        'label' => 'Riwayat Service Umum',
        'table' => 'maintenance_input_maintenance',
        'key' => 'id_key',
        'permission' => 'service.manage',
        'back' => '/riwayat-service-unit/service-umum',
        'fields' => [
            'nopol', 'area', 'driver', 'mode_service', 'tanggal_services', 'odo_services', 'keluhan',
            'tipe_service', 'spare_parts', 'jenis_spare_parts', 'harga_parts', 'nama_bengkel',
            'total_biaya_service', 'status_penbayaran', 'keterangan', 'nama',
        ],
        'import_enabled' => true,
        'import_required' => ['nopol', 'tanggal_services', 'tipe_service', 'total_biaya_service'],
        'import_date' => ['tanggal_services'],
        'import_uppercase' => ['nopol', 'tipe_service'],
        'import_numeric' => ['odo_services', 'harga_parts', 'total_biaya_service'],
        'import_references' => [
            'nopol' => [
                'table' => 'hr_manager_db_inventori',
                'column' => 'nopol',
                'label' => 'NOPOL',
            ],
            'tipe_service' => [
                'table' => 'dropdownlist_jenis_service',
                'column' => 'jenis_service',
                'label' => 'jenis service',
            ],
        ],
        'import_unique' => [['nopol', 'tanggal_services', 'tipe_service']],
        'import_instruction' => 'NOPOL harus terdaftar di inventori dan tipe service harus tersedia pada Master Jenis Service. Nominal dapat ditulis dalam format Indonesia, misalnya 1.250.000.',
    ],
    'service-ban' => [
        'label' => 'Riwayat Service Ban',
        'table' => 'maintenance_monitoring_ban',
        'key' => 'id_key',
        'permission' => 'service.manage',
        'back' => '/riwayat-service-unit/service-ban',
        'fields' => [
            'nopol', 'area', 'driver', 'tanggal_ganti_ban', 'jenis_pengerjaan', 'posisi',
            'kilometer_ganti_ban', 'kilometer_ganti_ban_sebelumnya', 'total_kilometer_pemakaian_ban',
            'qty_ban', 'no_seri_ban_lama', 'no_seri_ban_baru', 'jenis_ban', 'tipe_ban', 'harga_ban',
            'tools', 'ban_dalam', 'harga_ban_dalam', 'marset', 'harga_marset', 'total_harga',
            'nama_toko', 'keterangan', 'email',
        ],
        'import_enabled' => true,
        'import_required' => ['nopol', 'tanggal_ganti_ban', 'jenis_pengerjaan', 'posisi', 'kilometer_ganti_ban', 'qty_ban'],
        'import_date' => ['tanggal_ganti_ban'],
        'import_uppercase' => ['nopol', 'jenis_pengerjaan', 'posisi'],
        'import_numeric' => ['kilometer_ganti_ban', 'kilometer_ganti_ban_sebelumnya', 'harga_ban', 'harga_ban_dalam', 'harga_marset'],
        'import_integer' => ['qty_ban'],
        'import_text' => ['no_seri_ban_lama', 'no_seri_ban_baru'],
        'import_email' => ['email'],
        'import_references' => [
            'nopol' => [
                'table' => 'hr_manager_db_inventori',
                'column' => 'nopol',
                'label' => 'NOPOL',
            ],
        ],
        'import_unique' => [['nopol', 'tanggal_ganti_ban', 'posisi', 'jenis_pengerjaan']],
        'import_calculations' => [
            'total_kilometer_pemakaian_ban' => [
                'operation' => 'subtract',
                'left' => 'kilometer_ganti_ban',
                'right' => 'kilometer_ganti_ban_sebelumnya',
            ],
            'total_harga' => [
                'operation' => 'sum',
                'fields' => ['harga_ban', 'harga_ban_dalam', 'harga_marset'],
            ],
        ],
        'import_instruction' => 'NOPOL wajib terdaftar di inventori. Total kilometer pemakaian dan total harga dihitung ulang oleh sistem dari data kilometer serta komponen harga ban, ban dalam, dan marset.',
    ],
    'data-karyawan' => [
        'label' => 'Data Karyawan',
        'table' => 'hr_manager_db_pegawai',
        'key' => 'id_key',
        'permission' => 'employees.manage',
        'back' => '/daftar-karyawan',
        'fields' => [
            'nama_karyawan', 'nama_panggilan', 'nip', 'divisi', 'jabatan', 'level', 'area', 'agama', 'jenis_kelamin',
            'tempat_lahir', 'tanggal_lahir', 'umur', 'no_ponsel', 'no_ktp', 'no_kartu_keluarga', 'alamat_sesuai_ktp',
            'alamat_domisili', 'status_pernikahan', 'email', 'tanggal_bergabung', 'awal_pkwt', 'status_pkwt', 'akhir_pkwt',
            'masa_aktif', 'hari_aktif', 'jenis_sim', 'no_sim', 'masa_berlaku', 'status', 'nama_bank', 'rekening',
            'nama_pemilik_rekening', 'no_npwp', 'bpjk_kes', 'bpjs_tk', 'pendidikan', 'nama_sekolah_universitas', 'fakultas',
            'jurusan', 'nama_ayah_kandung', 'nama_ibu_kandung', 'nama_istri', 'nama_suami', 'jumlah_anak',
            'nama_anak_pertama', 'jenis_kelamin_anak_pertama', 'tanggal_lahir_anak_pertama', 'nama_anak_kedua',
            'jenis_kelamin_anak_kedua', 'tanggal_lahir_anak_kedua', 'nama_anak_ketiga', 'jenis_kelamin_anak_ketiga',
            'tanggal_lahir_anak_ketiga', 'nama_kerabat_1', 'hubungan_dengan_pekerja_1', 'nomor_telepon_atau_wa_1',
            'nama_kerabat_2', 'hubungan_dengan_pekerja_2', 'nomor_handphone_wa_2', 'ukuran_baju', 'ukuran_sepatu',
            'tarif_ovt', 'keterangan',
        ],
        'import_enabled' => true,
        'import_required' => ['nama_karyawan', 'nip', 'divisi', 'jabatan', 'area', 'tanggal_bergabung', 'status'],
        'import_date' => ['tanggal_lahir', 'tanggal_bergabung', 'awal_pkwt', 'akhir_pkwt', 'masa_berlaku', 'tanggal_lahir_anak_pertama', 'tanggal_lahir_anak_kedua', 'tanggal_lahir_anak_ketiga'],
        'import_numeric' => ['umur', 'masa_aktif', 'hari_aktif', 'jumlah_anak', 'tarif_ovt'],
        'import_text' => ['nip', 'no_ponsel', 'no_ktp', 'no_kartu_keluarga', 'no_sim', 'rekening', 'no_npwp', 'bpjk_kes', 'bpjs_tk', 'nomor_telepon_atau_wa_1', 'nomor_handphone_wa_2'],
        'import_email' => ['email'],
        'import_phone' => ['no_ponsel', 'nomor_telepon_atau_wa_1', 'nomor_handphone_wa_2'],
        'import_uppercase' => ['nip', 'status', 'status_pkwt'],
        'import_in' => [
            'status' => ['AKTIF', 'EXPIRED', 'HAMPIR EXPIRED'],
            'status_pkwt' => ['TETAP', 'PKWT'],
        ],
        'import_unique' => [['nip']],
        'import_instruction' => 'NIP adalah identitas utama dan wajib unik. Kolom sensitif seperti nomor KTP, rekening, dan NPWP harus diisi sebagai teks agar angka nol di depan tetap tersimpan. Status EXPIRED akan tampil pada arsip karyawan.',
    ],
    'finance-fat' => [
        'label' => 'Dokumen Finance',
        'table' => 'finance_accounting_tax_input_fat',
        'key' => 'id_key',
        'permission' => 'finance-documents.manage',
        'back' => '/finance/dokumen-invoice',
        'fields' => [
            'create_date', 'top', 'due_date', 'days', 'pao_week', 'regional', 'area', 'divisi', 'invoice_date',
            'no_invoice', 'vendor_supplier', 'dekripsi_invoice', 'invoice_amount', 'ppn', 'biaya_lainnya', 'pph',
            'total_payment', 'pengajuan', 'email', 'status_dokumen_asli',
        ],
        'import_enabled' => true,
        'import_required' => ['no_invoice', 'invoice_date', 'due_date', 'vendor_supplier', 'invoice_amount', 'status_dokumen_asli'],
        'import_date' => ['create_date', 'due_date', 'invoice_date'],
        'import_numeric' => ['top', 'days', 'pao_week', 'invoice_amount', 'ppn', 'biaya_lainnya', 'pph'],
        'import_text' => ['no_invoice'],
        'import_email' => ['email'],
        'import_uppercase' => ['no_invoice', 'status_dokumen_asli'],
        'import_map' => [
            'status_dokumen_asli' => [
                'BELUM LENGKAP' => 'KURANG',
                'BLANK' => 'BELUM DIUPLOAD',
            ],
        ],
        'import_in' => [
            'status_dokumen_asli' => ['LENGKAP', 'KURANG', 'BELUM DIUPLOAD'],
        ],
        'import_unique' => [['no_invoice']],
        'import_calculations' => [
            'total_payment' => [
                'operation' => 'sum_minus',
                'add' => ['invoice_amount', 'ppn', 'biaya_lainnya'],
                'subtract' => ['pph'],
            ],
        ],
        'import_instruction' => 'Status Invoice PAID, UNPAID, PARTIAL PAID, dan REFUND dihitung otomatis dari data pembayaran sehingga tidak perlu diisi pada file. Total payment dihitung ulang dari nominal invoice, PPN, biaya lainnya, dan PPh.',
    ],
    'upload-dokumen-operasional' => [
        'label' => 'Upload Dokumen Operasional',
        'table' => 'operasional_upload_dokumen',
        'key' => 'id_key',
        'permission' => 'approval.manage',
        'back' => '/need-approval',
        'fields' => ['add_data', 'nama', 'email', 'jenis_nota', 'foto_nota', 'nominal'],
    ],

    'dropdown-area' => [
        'label' => 'Dropdown Area',
        'table' => 'dropdownlist_area',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['area', 'regional'],
        'import_required' => ['area'],
        'import_enabled' => true,
    ],
    'kategori-barang-cargo' => [
        'label' => 'Kategori Barang Cargo',
        'table' => 'db_chargo_katagori_barang',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['nama_produk', 'jenis_produk'],
        'import_required' => ['nama_produk', 'jenis_produk'],
        'import_enabled' => true,
        'import_instruction' => 'Nama dan jenis produk wajib diisi agar kategori dapat dipakai pada proses pengiriman.',
    ],
    'daftar-ongkir-cargo' => [
        'label' => 'Daftar Ongkir Cargo',
        'table' => 'db_chargo_daftar_ongkir',
        'key' => 'no_id',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['kota_asal', 'kota_tujuan', 'satuan_berat', 'tarif'],
    ],
    'dropdown-area-fat' => [
        'label' => 'Dropdown Area FAT',
        'table' => 'dropdownlist_area_fat',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['area', 'regional'],
        'import_required' => ['area'],
        'import_enabled' => true,
    ],
    'dropdown-area-primary' => [
        'label' => 'Dropdown Area Primary',
        'table' => 'dropdownlist_area_primary',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['katagori', 'regional', 'area', 'ppn'],
        'import_required' => ['katagori', 'area'],
        'import_enabled' => true,
    ],
    'dropdown-area-rental' => [
        'label' => 'Dropdown Area Rental',
        'table' => 'dropdownlist_area_rental_unit',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['regional', 'area'],
        'import_required' => ['area'],
        'import_enabled' => true,
    ],
    'dropdown-divisi' => [
        'label' => 'Dropdown Divisi',
        'table' => 'dropdownlist_divisi',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['select_on', 'logo'],
        'import_required' => ['select_on'],
        'import_enabled' => true,
    ],
    'dropdown-fat-division' => [
        'label' => 'Dropdown FAT Division',
        'table' => 'dropdownlist_fat_division',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['division'],
        'import_required' => ['division'],
        'import_enabled' => true,
    ],
    'dropdown-jabatan' => [
        'label' => 'Dropdown Jabatan',
        'table' => 'dropdownlist_jabatan',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jabatan'],
        'import_required' => ['jabatan'],
        'import_enabled' => true,
    ],
    'dropdown-jenis-service' => [
        'label' => 'Dropdown Jenis Service',
        'table' => 'dropdownlist_jenis_service',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_service'],
        'import_required' => ['jenis_service'],
        'import_enabled' => true,
    ],
    'dropdown-jenis-unit' => [
        'label' => 'Dropdown Jenis Unit',
        'table' => 'dropdownlist_jenis_unit',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_unit'],
        'import_required' => ['jenis_unit'],
        'import_enabled' => true,
    ],
    'dropdown-sparepart' => [
        'label' => 'Dropdown Sparepart',
        'table' => 'dropdownlist_sparepart',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis', 'keterangan'],
        'import_required' => ['jenis'],
        'import_enabled' => true,
    ],
    'dropdown-tarif-primary' => [
        'label' => 'Dropdown Tarif Primary',
        'table' => 'dropdownlist_tarif_primary',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['kota_asal', 'kota_tujuan', 'tipe_unit', 'tarif_unit'],
        'import_required' => ['kota_asal', 'kota_tujuan', 'tipe_unit', 'tarif_unit'],
        'import_numeric' => ['tarif_unit'],
        'import_enabled' => true,
    ],
    'dropdown-violation' => [
        'label' => 'Dropdown Violation',
        'table' => 'dropdownlist_violation',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_pelanggaran', 'poin'],
        'import_required' => ['jenis_pelanggaran', 'poin'],
        'import_numeric' => ['poin'],
        'import_enabled' => true,
    ],
];
