<?php

return [
    'biaya-inventori' => [
        'label' => 'Biaya Legalitas Unit',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'biaya.manage',
        'back' => '/biaya',
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'project', 'tahun', 'tahun_pembelian', 'distribusi', 'status', 'keterangan',
            'jatuh_tempo_stnk', 'masa_aktif_stnk', 'status_stnk', 'biaya_stnk',
            'jatuh_tempo_pajak', 'masa_aktif_pajak', 'status_pajak', 'biaya_pajak',
            'jatuh_tempo_kir', 'masa_aktif_kir', 'status_kir', 'biaya_kir',
        ],
    ],
    'profit-primary' => [
        'label' => 'Profit Primary',
        'table' => 'operasional_primary_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/primary',
        'fields' => [
            'no_bap', 'regional', 'area', 'week', 'tanggal_muat', 'tanggal_terima', 'rute_asal', 'rute_tujuan',
            'vendor', 'nopol_driver', 'qty', 'jenis', 'total', 'no_po', 'no_si', 'no_sj', 'tarif',
            'total_tarif', 'tarif_vendor', 'total_biaya', 'profit', 'keterangan', 'status_dokument',
        ],
    ],
    'profit-secondary' => [
        'label' => 'Profit Secondary',
        'table' => 'operasional_secondary_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/secondary',
        'fields' => [
            'no_po', 'no_si', 'hari', 'tanggal', 'bulan', 'tahun', 'week', 'nopol', 'tipe_unit',
            'area', 'driver', 'helper', 'qty', 'order_type', 'tarif_unit', 'add_cost_long_route',
            'tkbm', 'spsi', 'parkir_liar_keamanan', 'allowance', 'total_tarif', 'total_biaya_operasional',
            'profit_trip', 'project', 'posisi_project', 'add_data',
        ],
    ],
    'profit-rental' => [
        'label' => 'Profit Rental',
        'table' => 'operasional_rental_unit_input',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/rental',
        'fields' => ['tanggal', 'no_bap', 'no_po', 'area', 'regional', 'nopol', 'tipe', 'tarif_sewa_unit_bln'],
    ],
    'profit-lcl' => [
        'label' => 'Profit LCL',
        'table' => 'db_chargo_data_paket_masuk',
        'key' => 'id_key',
        'permission' => 'profit-unit.manage',
        'back' => '/profit-unit/lcl',
        'fields' => [
            'no_stt', 'tanggal', 'tahun', 'bulan', 'week', 'kode_pesanan', 'nama_pengirim', 'kota_asal',
            'nama_penerima', 'kota_tujuan', 'total_koli', 'qty_unit', 'total_ongkir', 'jenis_ppn',
            'total_ppn', 'tagihan_cod', 'total_bayar', 'kembalian',
        ],
    ],
    'unit-inventori' => [
        'label' => 'Daftar Unit',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-unit',
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'gps', 'no_mesin', 'no_rangka', 'driver', 'project', 'tahun', 'tahun_pembelian',
            'distribusi', 'status', 'keterangan',
        ],
    ],
    'kendaraan-operasional' => [
        'label' => 'Kendaraan Operasional',
        'table' => 'hr_manager_db_inventori',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/kendaraan-operasional',
        'defaults' => [
            'project' => 'OPERASIONAL UNIT',
        ],
        'fields' => [
            'region', 'area', 'area_asal', 'inventaris', 'nopol', 'tipe', 'pabrikan', 'model', 'jenis',
            'gps', 'no_mesin', 'no_rangka', 'driver', 'project', 'tahun', 'tahun_pembelian',
            'distribusi', 'status', 'keterangan', 'foto_unit', 'status_stnk', 'status_pajak',
            'status_kir', 'my_pertamina',
        ],
    ],
    'asset-ho' => [
        'label' => 'Asset HO',
        'table' => 'hr_manager_inventaris_laptop',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/asset-ho',
        'fields' => [
            'nama_pengguna', 'katagori', 'jenis_barang', 'model_unit', 'divisi', 'lokasi',
            'jumlah_unit', 'pengguna_sebelumnya', 'spesifikasi', 'status', 'warna',
            'gambar', 'serial_number', 'keterangan',
        ],
    ],
    'toolkit' => [
        'label' => 'Toolkit',
        'table' => 'operasional_checklist',
        'key' => 'id_key',
        'permission' => 'inventory.manage',
        'back' => '/inventori/daftar-asset/toolkit',
        'fields' => [
            'tanggal', 'nopol', 'tipe_unit', 'area', 'driver', 'surat_kendaraan',
            'kebersihan_unit_kabin', 'kondisi_mesin_oli', 'service_berkala', 'air_radiator',
            'air_aki', 'kondisi_rem', 'indikator_dashboard', 'kondisi_kebersihan_box',
            'klakson', 'lampu_lampu', 'apar', 'safety_belt', 'p3k', 'dongkrak',
            'kunci_roda', 'engsel_pengunci_pintu', 'gembok', 'kondisi_ban',
            'tekanan_angin_ban', 'status_checklist', 'keluhan',
        ],
    ],
    'monitoring-unit' => [
        'label' => 'Monitoring Unit',
        'table' => 'operasional_update_posisi_unit',
        'key' => 'id',
        'permission' => 'on-the-road.manage',
        'back' => '/on-the-road',
        'fields' => ['tanggal_jam', 'nopol', 'nama_driver', 'location', 'keterangan'],
    ],
    'finance-fat' => [
        'label' => 'Dokumen Finance',
        'table' => 'finance_accounting_tax_input_fat',
        'key' => 'id_key',
        'permission' => 'finance-documents.manage',
        'back' => '/finance/dokumen-invoice',
        'fields' => [
            'create_date', 'due_date', 'regional', 'area', 'divisi', 'invoice_date', 'no_invoice',
            'vendor_supplier', 'dekripsi_invoice', 'invoice_amount', 'ppn', 'pph', 'total_payment',
            'pengajuan', 'status_dokumen_asli',
        ],
    ],
    'upload-dokumen-operasional' => [
        'label' => 'Upload Dokumen Operasional',
        'table' => 'operasional_upload_dokumen',
        'key' => 'id_key',
        'permission' => 'approval.manage',
        'back' => '/need-approval',
        'fields' => ['add_data', 'nama', 'email', 'jenis_nota', 'foto_nota', 'nominal'],
    ],

    'dropdown-area' => [
        'label' => 'Dropdown Area',
        'table' => 'dropdownlist_area',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['area', 'regional'],
    ],
    'dropdown-area-fat' => [
        'label' => 'Dropdown Area FAT',
        'table' => 'dropdownlist_area_fat',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['area', 'regional'],
    ],
    'dropdown-area-primary' => [
        'label' => 'Dropdown Area Primary',
        'table' => 'dropdownlist_area_primary',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['katagori', 'regional', 'area', 'ppn'],
    ],
    'dropdown-area-rental' => [
        'label' => 'Dropdown Area Rental',
        'table' => 'dropdownlist_area_rental_unit',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['regional', 'area'],
    ],
    'dropdown-divisi' => [
        'label' => 'Dropdown Divisi',
        'table' => 'dropdownlist_divisi',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['select_on', 'logo'],
    ],
    'dropdown-fat-division' => [
        'label' => 'Dropdown FAT Division',
        'table' => 'dropdownlist_fat_division',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['division'],
    ],
    'dropdown-jabatan' => [
        'label' => 'Dropdown Jabatan',
        'table' => 'dropdownlist_jabatan',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jabatan'],
    ],
    'dropdown-jenis-service' => [
        'label' => 'Dropdown Jenis Service',
        'table' => 'dropdownlist_jenis_service',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_service'],
    ],
    'dropdown-jenis-unit' => [
        'label' => 'Dropdown Jenis Unit',
        'table' => 'dropdownlist_jenis_unit',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_unit'],
    ],
    'dropdown-sparepart' => [
        'label' => 'Dropdown Sparepart',
        'table' => 'dropdownlist_sparepart',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis', 'keterangan'],
    ],
    'dropdown-tarif-primary' => [
        'label' => 'Dropdown Tarif Primary',
        'table' => 'dropdownlist_tarif_primary',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['kota_asal', 'kota_tujuan', 'tipe_unit', 'tarif_unit'],
    ],
    'dropdown-violation' => [
        'label' => 'Dropdown Violation',
        'table' => 'dropdownlist_violation',
        'key' => 'id_key',
        'permission' => 'system.manage',
        'back' => '/module-records',
        'fields' => ['jenis_pelanggaran', 'poin'],
    ],
];
