import React, { memo, useMemo, useState } from "react";
import AdminLayout from "../../Layouts/AdminLayout";
import { Head, Link, router } from "@inertiajs/react";
import { BarChart, Bar, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowRight, BarChart3, Building2, CircleDollarSign, Landmark, TrendingDown, TrendingUp, WalletCards } from "lucide-react";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"];
const formatRp = (value) => `Rp${Number(value || 0).toLocaleString("id-ID", { maximumFractionDigits: 0 })}`;
const formatNum = (value) => Number(value || 0).toLocaleString("id-ID");
const formatCompactRp = (value) => {
    const amount = Number(value || 0);
    if (Math.abs(amount) >= 1_000_000_000) return `Rp${(amount / 1_000_000_000).toLocaleString("id-ID", { maximumFractionDigits: 1 })} M`;
    if (Math.abs(amount) >= 1_000_000) return `Rp${(amount / 1_000_000).toLocaleString("id-ID", { maximumFractionDigits: 0 })} jt`;
    return formatRp(amount);
};

const Card = ({ children, className = "" }) => <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/60 ${className}`}>{children}</section>;

const MetricCard = memo(function MetricCard({ label, value, fullValue, icon: Icon, tone, helper }) {
    return <Card className="min-w-0 w-full p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-wider text-slate-500">{label}</p><p title={fullValue ?? value} className="mt-2 min-w-0 truncate text-[clamp(1.05rem,1.6vw,1.55rem)] font-black tracking-tight text-slate-950 tabular-nums">{value}</p><p className="mt-1 text-xs font-semibold text-slate-400">{helper}</p></div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tone}`}><Icon size={20} /></span></div></Card>;
});

function areaStatus(area) {
    const revenue = Number(area.revenue || 0);
    const profit = Number(area.profit || 0);
    const margin = revenue > 0 ? profit / revenue * 100 : null;
    if (margin === null) return ["Perlu Dicek", "bg-slate-100 text-slate-600"];
    if (profit < 0) return ["Loss", "bg-rose-50 text-rose-700"];
    if (margin >= 60) return ["Excellent", "bg-emerald-50 text-emerald-700"];
    if (margin >= 30) return ["Normal", "bg-cyan-50 text-cyan-700"];
    return ["Rendah", "bg-amber-50 text-amber-700"];
}

function AreaCards({ areas }) {
    return <div className="space-y-3 md:hidden">{areas.map((area) => { const margin = area.revenue > 0 ? area.profit / area.revenue * 100 : null; const [status, tone] = areaStatus(area); return <div key={area.area} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between gap-3"><p className="font-black text-slate-900">{area.area}</p><span className={`rounded-md px-2 py-1 text-[10px] font-black ${tone}`}>{status}</span></div><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Revenue</dt><dd className="mt-1 font-bold text-slate-700">{formatCompactRp(area.revenue)}</dd></div><div><dt className="text-slate-400">Cost</dt><dd className="mt-1 font-bold text-slate-700">{formatCompactRp(area.cost)}</dd></div><div><dt className="text-slate-400">Profit</dt><dd className="mt-1 font-black text-emerald-700">{formatCompactRp(area.profit)}</dd></div><div><dt className="text-slate-400">Margin · Record</dt><dd className="mt-1 font-bold text-slate-700">{margin === null ? "—" : `${margin.toFixed(1)}%`} · {formatNum(area.records)}</dd></div></dl></div>; })}</div>;
}

export default function Performance({ dbChartData, performanceData, selectedYear = null, availableYears = [] }) {
    const year = selectedYear ? String(selectedYear) : "all";
    const summary = performanceData?.summary || { revenue: 0, cost: 0, profit: 0, margin: 0 };
    const areas = useMemo(() => [...(performanceData?.areas || [])].sort((a, b) => Number(b.profit) - Number(a.profit)), [performanceData]);
    const modules = performanceData?.modules || [];
    const years = availableYears;
    const trend = useMemo(() => (performanceData?.monthly || []).map((item) => ({ ...item, label: year === "all" ? `${MONTHS[item.bulan - 1]} ${item.tahun}` : MONTHS[item.bulan - 1] })), [performanceData, year]);
    const topAreas = areas.slice(0, 5);
    const lowestMargin = areas.filter((area) => Number(area.revenue) > 0).sort((a, b) => (a.profit / a.revenue) - (b.profit / b.revenue))[0];
    const topModule = [...modules].sort((a, b) => Number(b.profit) - Number(a.profit))[0];
    const highestCostModule = [...modules].sort((a, b) => Number(b.cost) - Number(a.cost))[0];
    const totalUnit = (dbChartData?.pajak || []).reduce((sum, item) => sum + Number(item.value || 0), 0);
    const activeDocs = [dbChartData?.pajak, dbChartData?.stnk, dbChartData?.kir].reduce((sum, items) => sum + Number(items?.find((item) => item.name === "AKTIF")?.value || 0), 0);
    const health = totalUnit > 0 ? activeDocs / (totalUnit * 3) * 100 : null;
    const periodLabel = year === "all" ? "Menampilkan seluruh data historis" : `Menampilkan performa untuk tahun ${year}`;
    const changeYear = (value) => router.get("/business-control/performance", value === "all" ? {} : { tahun: value }, { preserveScroll: true, preserveState: true });

    return <AdminLayout><Head title="Business Performance" /><div className="space-y-6 font-[Manrope]">
        <header className="flex flex-col gap-4 min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><span className="inline-flex rounded-full bg-cyan-50 px-3 py-1 text-[11px] font-bold text-cyan-700">Business control</span><h1 className="mt-3 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl truncate">Business Performance</h1><p className="mt-1 text-sm font-semibold text-slate-500">Kontrol pendapatan, biaya, profit, dan margin Washeng GO.</p><p className="mt-2 text-xs font-bold text-slate-400">{periodLabel}</p></div><div className="flex items-center gap-2 shrink-0"><label className="text-xs font-bold text-slate-500 hidden sm:inline">Periode</label><select value={year} onChange={(event) => changeYear(event.target.value)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700"> <option value="all">Semua tahun</option>{years.map((item) => <option key={item} value={item}>{item}</option>)}</select></div></header>
        <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 2xl:grid-cols-4"><MetricCard label="Revenue" value={formatCompactRp(summary.revenue)} fullValue={formatRp(summary.revenue)} helper="Total pendapatan tercatat" icon={Landmark} tone="bg-cyan-50 text-cyan-700" /><MetricCard label="Cost" value={formatCompactRp(summary.cost)} fullValue={formatRp(summary.cost)} helper="Total biaya operasional" icon={WalletCards} tone="bg-amber-50 text-amber-700" /><MetricCard label="Profit" value={formatCompactRp(summary.profit)} fullValue={formatRp(summary.profit)} helper="Revenue dikurangi cost" icon={CircleDollarSign} tone="bg-emerald-50 text-emerald-700" /><MetricCard label="Margin" value={`${Number(summary.margin || 0).toFixed(1)}%`} helper="Rasio profit periode aktif" icon={TrendingUp} tone="bg-violet-50 text-violet-700" /></div>
        <div className="grid gap-6 2xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><Card className="p-5 min-w-0"><div className="mb-5"><h2 className="text-base font-black text-slate-950">Trend Revenue, Cost, Profit</h2><p className="mt-1 text-xs font-semibold text-slate-500">Akumulasi finansial bulanan dari data transaksi valid.</p></div>{trend.length ? <div className="h-72 w-full min-w-0"><ResponsiveContainer><LineChart data={trend} margin={{ top: 8, right: 6, left: 0, bottom: 0 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis tickFormatter={formatCompactRp} tick={{ fontSize: 10, fill: "#64748b" }} axisLine={false} tickLine={false} width={64} /><Tooltip formatter={(value, name) => [formatRp(value), name]} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0", fontSize: 12 }} /><Legend wrapperStyle={{ fontSize: 12 }} /><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#0891b2" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="cost" name="Cost" stroke="#d97706" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="profit" name="Profit" stroke="#059669" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></div> : <p className="py-24 text-center text-sm font-semibold text-slate-400">Trend finansial belum tersedia.</p>}</Card>
        <Card className="p-5 min-w-0"><div className="flex items-center gap-2"><BarChart3 size={18} className="text-violet-600" /><div><h2 className="font-black text-slate-950">Insight Performa</h2><p className="text-xs font-semibold text-slate-500">Ringkasan prioritas bisnis.</p></div></div>{areas.length || modules.length ? <div className="mt-5 space-y-4 text-sm">{[["Area profit tertinggi", topAreas[0]?.area, topAreas[0]?.profit, TrendingUp], ["Area margin terendah", lowestMargin?.area, lowestMargin && `${(lowestMargin.profit / lowestMargin.revenue * 100).toFixed(1)}%`, TrendingDown], ["Modul profit tertinggi", topModule?.module, topModule?.profit, Building2], ["Biaya terbesar", highestCostModule?.module, highestCostModule?.cost, WalletCards]].map(([label, name, value, Icon]) => <div key={label} className="flex gap-3 min-w-0"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-600"><Icon size={16} /></span><div className="min-w-0"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-0.5 truncate font-black text-slate-900">{name || "Belum tersedia"}{value !== undefined && value !== null ? <span className="font-bold text-slate-500"> — {typeof value === "number" ? formatCompactRp(value) : value}</span> : null}</p></div></div>)}</div> : <p className="py-20 text-center text-sm font-semibold text-slate-400">Data insight belum tersedia untuk periode ini.</p>}</Card></div>
        <div className="grid gap-6 2xl:grid-cols-2"><Card className="p-5 min-w-0"><div className="mb-5"><h2 className="font-black text-slate-950">Top Area by Profit</h2><p className="mt-1 text-xs font-semibold text-slate-500">Lima area dengan profit tertinggi.</p></div>{topAreas.length ? <div className="h-72 w-full min-w-0"><ResponsiveContainer><BarChart data={topAreas} layout="vertical" margin={{ left: 0, right: 8 }}><XAxis type="number" tickFormatter={formatCompactRp} tick={{ fontSize: 10, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="area" width={88} tick={{ fontSize: 11, fontWeight: 700, fill: "#334155" }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => [formatRp(value), "Profit"]} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0", fontSize: 12 }} /><Bar dataKey="profit" fill="#059669" radius={[0, 6, 6, 0]} barSize={18} /></BarChart></ResponsiveContainer></div> : <p className="py-24 text-center text-sm font-semibold text-slate-400">Belum ada data area.</p>}<div className="mt-2 grid gap-2 sm:grid-cols-2">{topAreas.map((area) => <p key={area.area} className="truncate text-xs font-semibold text-slate-500"><span className="font-black text-slate-800">{area.area}</span> · Margin {area.revenue > 0 ? `${(area.profit / area.revenue * 100).toFixed(1)}%` : "—"} · {formatNum(area.records)} record</p>)}</div></Card>
        <Card className="p-5 min-w-0"><div className="mb-5"><h2 className="font-black text-slate-950">Performance per Modul</h2><p className="mt-1 text-xs font-semibold text-slate-500">Gunakan formula sumber masing-masing modul.</p></div>{modules.length ? <div className="grid gap-3 sm:grid-cols-2">{modules.map((module) => <div key={module.module} className="rounded-xl border border-slate-100 bg-slate-50 p-4 min-w-0"><p className="font-black text-slate-950 truncate">{module.module}</p><p className="mt-2 text-lg font-black text-emerald-700">{formatCompactRp(module.profit)}</p><p className="text-[11px] font-bold text-slate-500">Profit</p><dl className="mt-3 space-y-1 text-xs font-semibold text-slate-600"><div className="flex justify-between gap-2"><dt>Revenue</dt><dd>{formatCompactRp(module.revenue)}</dd></div><div className="flex justify-between gap-2"><dt>Cost</dt><dd>{formatCompactRp(module.cost)}</dd></div><div className="flex justify-between gap-2"><dt>Margin · Record</dt><dd>{module.margin === null ? "—" : `${Number(module.margin).toFixed(1)}%`} · {formatNum(module.records)}</dd></div></dl></div>)}</div> : <p className="py-24 text-center text-sm font-semibold text-slate-400">Data modul belum tersedia untuk periode ini.</p>}</Card></div>
        <Card className="min-w-0"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-slate-950">Area Performance</h2><p className="mt-1 text-xs font-semibold text-slate-500">Analisis profitabilitas area, read-only.</p></div><AreaCards areas={areas} /><div className="hidden overflow-x-auto md:block min-w-0"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr>{["Area", "Revenue", "Cost", "Profit", "Margin", "Record", "Profit / Record", "Status"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{areas.length ? areas.map((area) => { const margin = area.revenue > 0 ? area.profit / area.revenue * 100 : null; const [status, tone] = areaStatus(area); return <tr key={area.area} className="font-semibold text-slate-600 hover:bg-slate-50/70"><td className="px-4 py-3 font-black text-slate-900">{area.area}</td><td className="px-4 py-3 whitespace-nowrap">{formatRp(area.revenue)}</td><td className="px-4 py-3 whitespace-nowrap">{formatRp(area.cost)}</td><td className="px-4 py-3 whitespace-nowrap font-black text-emerald-700">{formatRp(area.profit)}</td><td className="px-4 py-3">{margin === null ? "—" : `${margin.toFixed(1)}%`}</td><td className="px-4 py-3">{formatNum(area.records)}</td><td className="px-4 py-3 whitespace-nowrap">{area.records ? formatRp(area.profit / area.records) : "—"}</td><td className="px-4 py-3"><span className={`rounded-md px-2 py-1 text-[10px] font-black ${tone}`}>{status}</span></td></tr>; }) : <tr><td colSpan={8} className="px-4 py-12 text-center text-sm font-semibold text-slate-400">Belum ada data area untuk periode ini.</td></tr>}</tbody></table></div></Card>
        <Card className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black text-slate-900">Data & Document Health</p><p className="mt-1 text-xs font-semibold text-slate-500">{health === null ? "Data kepatuhan global belum tersedia" : `${health.toFixed(1)}% dokumen kendaraan aktif`} · Data ini bersifat global dan tidak ikut filter periode.</p></div><Link href="/business-control/health" className="inline-flex w-fit items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs font-black text-slate-700 transition hover:bg-slate-200">Lihat Data Health <ArrowRight size={14} /></Link></Card>
    </div></AdminLayout>;
}
